---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatgpt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk-sas
